param(
  [string]$TaskName = "CodexBridge-Codex",
  [string]$RootDir = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
  [string]$StateDir = "",
  [string]$EnvFile = "",
  [string]$HomeDir = "",
  [string]$DefaultCwd = ""
)

$ErrorActionPreference = "Stop"

function Find-CommandPath([string[]]$Names) {
  foreach ($Name in $Names) {
    $Command = Get-Command $Name -ErrorAction SilentlyContinue
    if ($Command) {
      return $Command.Source
    }
  }
  return ""
}

function Resolve-ServiceHomeDir([string]$RequestedHomeDir, [string]$ResolvedRootDir) {
  if ($RequestedHomeDir) {
    $Resolved = Resolve-Path $RequestedHomeDir -ErrorAction SilentlyContinue
    if ($Resolved) {
      return $Resolved.Path
    }
    return $RequestedHomeDir
  }
  if ($env:USERPROFILE) {
    return $env:USERPROFILE
  }
  $RootMatch = [regex]::Match($ResolvedRootDir, "^[A-Za-z]:\\Users\\[^\\]+")
  if ($RootMatch.Success) {
    return $RootMatch.Value
  }
  throw "Could not resolve service home directory. Pass -HomeDir explicitly."
}

function Resolve-ServiceAppData([string]$ResolvedHomeDir) {
  if ($env:APPDATA -and $env:APPDATA -notlike "*\systemprofile\*") {
    return $env:APPDATA
  }
  return Join-Path $ResolvedHomeDir "AppData\Roaming"
}

function Ensure-EnvLine([string]$Path, [string]$Key, [string]$Value) {
  $Content = Get-Content -Path $Path -Raw -ErrorAction SilentlyContinue
  if ($Content -notmatch "(?m)^$([regex]::Escape($Key))=") {
    Add-Content -Encoding UTF8 -Path $Path -Value "$Key=$Value"
  }
}

function Set-EnvLine([string]$Path, [string]$Key, [string]$Value) {
  $Content = Get-Content -Path $Path -Raw -ErrorAction SilentlyContinue
  if ($Content -match "(?m)^$([regex]::Escape($Key))=") {
    $Content = $Content -replace "(?m)^$([regex]::Escape($Key))=.*$", "$Key=$Value"
    Set-Content -Encoding UTF8 -Path $Path -Value $Content
  } else {
    Add-Content -Encoding UTF8 -Path $Path -Value "$Key=$Value"
  }
}

function Stop-MatchingNodeProcesses([string]$ResolvedRootDir, [string[]]$Markers) {
  $RootPattern = "*$($ResolvedRootDir)*"
  Get-CimInstance Win32_Process -Filter "name = 'node.exe'" |
    Where-Object {
      $CommandLine = $_.CommandLine
      if (-not $CommandLine -or $CommandLine -notlike $RootPattern) {
        return $false
      }
      foreach ($Marker in $Markers) {
        if ($CommandLine -like "*$Marker*") {
          return $true
        }
      }
      return $false
    } |
    ForEach-Object {
      Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue
    }
}

$NodeBin = Find-CommandPath @("node.exe", "node")
if (-not $NodeBin) {
  throw "node was not found in PATH"
}

$HomeDir = Resolve-ServiceHomeDir $HomeDir $RootDir
if (-not $StateDir) {
  $StateDir = Join-Path $HomeDir ".codexbridge"
}
if (-not $EnvFile) {
  $EnvFile = Join-Path (Resolve-ServiceAppData $HomeDir) "codexbridge\weixin.service.env"
}
if (-not $DefaultCwd) {
  $DefaultCwd = Join-Path $HomeDir "Documents"
}

$NpmCodexBin = Join-Path (Resolve-ServiceAppData $HomeDir) "npm\codex.cmd"
$CodexBin = if (Test-Path $NpmCodexBin) {
  $NpmCodexBin
} else {
  Find-CommandPath @("codex.cmd", "codex.bat", "codex.exe", "codex")
}
$ConfigDir = Split-Path -Parent $EnvFile
$LogDir = Join-Path $StateDir "logs"
$StdoutLog = Join-Path $LogDir "codex-native-api.out.log"
$StderrLog = Join-Path $LogDir "codex-native-api.err.log"
$CodexHome = Join-Path $HomeDir ".codex"

New-Item -ItemType Directory -Force -Path $ConfigDir, $LogDir | Out-Null

if (-not (Test-Path $EnvFile)) {
  @(
    "# Generated by scripts/service/install-windows-codex-task.ps1",
    "# Safe to edit after install.",
    "",
    "CODEX_DEFAULT_PROVIDER_PROFILE_ID=openai-default",
    "CODEX_HOME=$CodexHome",
    "CODEX_REAL_BIN=$CodexBin",
    "",
    "CODEX_NATIVE_API_ENABLE=0",
    "CODEX_NATIVE_API_HOST=127.0.0.1",
    "CODEX_NATIVE_API_PORT=43182",
    "CODEX_NATIVE_API_PROVIDER_PROFILE_ID=",
    "CODEX_NATIVE_API_PROVIDER_PROFILE=",
    "CODEXBRIDGE_INTERNAL_NATIVE_API_BASE_URL=http://127.0.0.1:43182"
  ) | Set-Content -Encoding UTF8 -Path $EnvFile
} else {
  Ensure-EnvLine $EnvFile "CODEX_HOME" $CodexHome
  Set-EnvLine $EnvFile "CODEX_REAL_BIN" $CodexBin
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_ENABLE" "0"
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_HOST" "127.0.0.1"
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_PORT" "43182"
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_PROVIDER_PROFILE_ID" ""
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_PROVIDER_PROFILE" ""
  Set-EnvLine $EnvFile "CODEXBRIDGE_INTERNAL_NATIVE_API_BASE_URL" "http://127.0.0.1:43182"
}

$Runner = Join-Path $RootDir "scripts\service\run-codex-native-api-service.mjs"
$HiddenRunner = Join-Path $RootDir "scripts\service\run-codex-native-api-windows-task.ps1"

$PowerShellBin = (Get-Command powershell.exe -ErrorAction Stop).Source
$TaskArguments = @(
  "-NoProfile",
  "-ExecutionPolicy", "Bypass",
  "-WindowStyle", "Hidden",
  "-File", "`"$HiddenRunner`"",
  "-NodeBin", "`"$NodeBin`"",
  "-Runner", "`"$Runner`"",
  "-RootDir", "`"$RootDir`"",
  "-HomeDir", "`"$HomeDir`"",
  "-StateDir", "`"$StateDir`"",
  "-EnvFile", "`"$EnvFile`"",
  "-StdoutLog", "`"$StdoutLog`"",
  "-StderrLog", "`"$StderrLog`"",
  "-DefaultCwd", "`"$DefaultCwd`""
)

$Action = New-ScheduledTaskAction -Execute $PowerShellBin -Argument ($TaskArguments -join " ")
$CurrentIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
$Trigger = New-ScheduledTaskTrigger -AtLogOn -User $CurrentIdentity
$Settings = New-ScheduledTaskSettingsSet `
  -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries `
  -ExecutionTimeLimit (New-TimeSpan -Days 3650) `
  -MultipleInstances IgnoreNew `
  -RestartCount 999 `
  -RestartInterval (New-TimeSpan -Minutes 1) `
  -StartWhenAvailable
$Principal = New-ScheduledTaskPrincipal -UserId $CurrentIdentity -LogonType Interactive -RunLevel Highest

Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
Start-Sleep -Milliseconds 500
Stop-MatchingNodeProcesses $RootDir @("run-codex-native-api-service.mjs", "native-api-serve")

Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal -Force | Out-Null
Start-ScheduledTask -TaskName $TaskName

Write-Host "Installed scheduled task: $TaskName"
Write-Host "Run as: $($Principal.UserId)"
Write-Host "Home dir: $HomeDir"
Write-Host "Environment file: $EnvFile"
Write-Host "Stdout log: $StdoutLog"
Write-Host "Stderr log: $StderrLog"
