param(
  [string]$TaskName = "CodexBridge-Weixin",
  [string]$RootDir = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
  [string]$StateDir = "",
  [string]$EnvFile = "",
  [string]$HomeDir = "",
  [string]$DefaultCwd = "",
  [string]$WeixinAccountId = "",
  [switch]$AtStartup
)

$ErrorActionPreference = "Stop"

function Find-CommandPath([string[]]$Names) {
  foreach ($Name in $Names) {
    $Command = Get-Command $Name -ErrorAction SilentlyContinue
    if ($Command) {
      return $Command.Source
    }
  }
  return ""
}

function Resolve-ServiceHomeDir([string]$RequestedHomeDir, [string]$ResolvedRootDir) {
  if ($RequestedHomeDir) {
    $Resolved = Resolve-Path $RequestedHomeDir -ErrorAction SilentlyContinue
    if ($Resolved) {
      return $Resolved.Path
    }
    return $RequestedHomeDir
  }

  if ($env:CODEXBRIDGE_SERVICE_HOME) {
    $Resolved = Resolve-Path $env:CODEXBRIDGE_SERVICE_HOME -ErrorAction SilentlyContinue
    if ($Resolved) {
      return $Resolved.Path
    }
    return $env:CODEXBRIDGE_SERVICE_HOME
  }

  $CurrentIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
  if ($CurrentIdentity -ne "NT AUTHORITY\SYSTEM" -and $env:USERPROFILE) {
    return $env:USERPROFILE
  }

  $RootMatch = [regex]::Match($ResolvedRootDir, "^[A-Za-z]:\\Users\\[^\\]+")
  if ($RootMatch.Success) {
    return $RootMatch.Value
  }

  try {
    $LoggedOnUser = (Get-CimInstance Win32_ComputerSystem).UserName
    if ($LoggedOnUser -and $LoggedOnUser.Contains("\")) {
      $UserName = $LoggedOnUser.Split("\")[-1]
      $Candidate = Join-Path (Join-Path $env:SystemDrive "Users") $UserName
      if (Test-Path $Candidate) {
        return $Candidate
      }
    }
  } catch {}

  if ($env:USERPROFILE) {
    return $env:USERPROFILE
  }

  throw "Could not resolve service home directory. Pass -HomeDir explicitly."
}

function Resolve-ServiceAppData([string]$ResolvedHomeDir) {
  if ($env:APPDATA -and $env:APPDATA -notlike "*\systemprofile\*") {
    return $env:APPDATA
  }
  return Join-Path $ResolvedHomeDir "AppData\Roaming"
}

function Ensure-EnvLine([string]$Path, [string]$Key, [string]$Value) {
  $Content = Get-Content -Path $Path -Raw -ErrorAction SilentlyContinue
  if ($Content -notmatch "(?m)^$([regex]::Escape($Key))=") {
    Add-Content -Encoding UTF8 -Path $Path -Value "$Key=$Value"
  }
}

function Set-EnvLine([string]$Path, [string]$Key, [string]$Value) {
  $Content = Get-Content -Path $Path -Raw -ErrorAction SilentlyContinue
  if ($Content -match "(?m)^$([regex]::Escape($Key))=") {
    $Content = $Content -replace "(?m)^$([regex]::Escape($Key))=.*$", "$Key=$Value"
    Set-Content -Encoding UTF8 -Path $Path -Value $Content
  } else {
    Add-Content -Encoding UTF8 -Path $Path -Value "$Key=$Value"
  }
}

function Stop-MatchingNodeProcesses([string]$ResolvedRootDir, [string[]]$Markers) {
  $RootPattern = "*$($ResolvedRootDir)*"
  Get-CimInstance Win32_Process -Filter "name = 'node.exe'" |
    Where-Object {
      $CommandLine = $_.CommandLine
      if (-not $CommandLine -or $CommandLine -notlike $RootPattern) {
        return $false
      }
      foreach ($Marker in $Markers) {
        if ($CommandLine -like "*$Marker*") {
          return $true
        }
      }
      return $false
    } |
    ForEach-Object {
      Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue
    }
}

$NodeBin = Find-CommandPath @("node.exe", "node")
if (-not $NodeBin) {
  throw "node was not found in PATH"
}

$HomeDir = Resolve-ServiceHomeDir $HomeDir $RootDir
if (-not $StateDir) {
  $StateDir = Join-Path $HomeDir ".codexbridge"
}
if (-not $EnvFile) {
  $EnvFile = Join-Path (Resolve-ServiceAppData $HomeDir) "codexbridge\weixin.service.env"
}

$NpmCodexBin = Join-Path (Resolve-ServiceAppData $HomeDir) "npm\codex.cmd"
$CodexBin = if (Test-Path $NpmCodexBin) {
  $NpmCodexBin
} else {
  Find-CommandPath @("codex.cmd", "codex.bat", "codex.exe", "codex")
}
$ConfigDir = Split-Path -Parent $EnvFile
$LogDir = Join-Path $StateDir "logs"
$StdoutLog = Join-Path $LogDir "weixin-bridge.out.log"
$StderrLog = Join-Path $LogDir "weixin-bridge.err.log"
$CodexHome = Join-Path $HomeDir ".codex"
$AccountsDir = Join-Path $StateDir "weixin\accounts"

if (-not $WeixinAccountId) {
  $WeixinAccountId = $env:WEIXIN_ACCOUNT_ID
}
if (-not $WeixinAccountId -and (Test-Path $AccountsDir)) {
  $LatestAccount = Get-ChildItem -Path $AccountsDir -File -Filter "*.json" |
    Where-Object {
      $_.Name -notlike "*.context-tokens.json" -and
      $_.Name -notlike "*.sync.json"
    } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1
  if ($LatestAccount) {
    $WeixinAccountId = $LatestAccount.BaseName
  }
}

New-Item -ItemType Directory -Force -Path $ConfigDir, $LogDir | Out-Null

if (-not (Test-Path $EnvFile)) {
  @(
    "# Generated by scripts/service/install-windows-task.ps1",
    "# Safe to edit after install.",
    "",
    "WEIXIN_ACCOUNT_ID=$WeixinAccountId",
    "WEIXIN_DM_POLICY=open",
    "WEIXIN_GROUP_POLICY=disabled",
    "",
    "CODEX_DEFAULT_PROVIDER_PROFILE_ID=openai-default",
    "CODEX_HOME=$CodexHome",
    "CODEX_REAL_BIN=$CodexBin",
    "",
    "CODEX_NATIVE_API_ENABLE=0",
    "CODEX_NATIVE_API_HOST=127.0.0.1",
    "CODEX_NATIVE_API_PORT=43182",
    "CODEX_NATIVE_API_PROVIDER_PROFILE_ID=",
    "CODEXBRIDGE_INTERNAL_NATIVE_API_BASE_URL=http://127.0.0.1:43182",
    "",
    "CODEXBRIDGE_DEBUG_WEIXIN=0",
    "CODEXBRIDGE_SERVICE_LOG_MAX_MB=20",
    "CODEXBRIDGE_SERVICE_LOG_FILES=3"
  ) | Set-Content -Encoding UTF8 -Path $EnvFile
} else {
  if ($WeixinAccountId) {
    Set-EnvLine $EnvFile "WEIXIN_ACCOUNT_ID" $WeixinAccountId
  }
  Ensure-EnvLine $EnvFile "CODEX_HOME" $CodexHome
  Set-EnvLine $EnvFile "CODEX_REAL_BIN" $CodexBin
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_ENABLE" "0"
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_HOST" "127.0.0.1"
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_PORT" "43182"
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_PROVIDER_PROFILE_ID" ""
  Set-EnvLine $EnvFile "CODEX_NATIVE_API_PROVIDER_PROFILE" ""
  Set-EnvLine $EnvFile "CODEXBRIDGE_INTERNAL_NATIVE_API_BASE_URL" "http://127.0.0.1:43182"
  Ensure-EnvLine $EnvFile "CODEXBRIDGE_SERVICE_LOG_MAX_MB" "20"
  Ensure-EnvLine $EnvFile "CODEXBRIDGE_SERVICE_LOG_FILES" "3"
}

$Runner = Join-Path $RootDir "scripts\service\run-weixin-service.mjs"
$HiddenRunner = Join-Path $RootDir "scripts\service\run-weixin-service-windows-task.ps1"

$PowerShellBin = (Get-Command powershell.exe -ErrorAction Stop).Source
$TaskArguments = @(
  "-NoProfile",
  "-ExecutionPolicy", "Bypass",
  "-WindowStyle", "Hidden",
  "-File", "`"$HiddenRunner`"",
  "-NodeBin", "`"$NodeBin`"",
  "-Runner", "`"$Runner`"",
  "-RootDir", "`"$RootDir`"",
  "-HomeDir", "`"$HomeDir`"",
  "-StateDir", "`"$StateDir`"",
  "-EnvFile", "`"$EnvFile`"",
  "-StdoutLog", "`"$StdoutLog`"",
  "-StderrLog", "`"$StderrLog`""
)
if ($DefaultCwd) {
  $TaskArguments += @("-DefaultCwd", "`"$DefaultCwd`"")
}

$Action = New-ScheduledTaskAction -Execute $PowerShellBin -Argument ($TaskArguments -join " ")
$CurrentIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
$RunAsSystem = $CurrentIdentity -eq "NT AUTHORITY\SYSTEM"

if ($AtStartup -or $RunAsSystem) {
  $Trigger = New-ScheduledTaskTrigger -AtStartup
} else {
  $Trigger = New-ScheduledTaskTrigger -AtLogOn -User $CurrentIdentity
}
$Settings = New-ScheduledTaskSettingsSet `
  -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries `
  -ExecutionTimeLimit (New-TimeSpan -Days 3650) `
  -MultipleInstances IgnoreNew `
  -RestartCount 999 `
  -RestartInterval (New-TimeSpan -Minutes 1) `
  -StartWhenAvailable

if ($RunAsSystem) {
  $Principal = New-ScheduledTaskPrincipal -UserId "NT AUTHORITY\SYSTEM" -LogonType ServiceAccount -RunLevel Highest
} else {
  $Principal = New-ScheduledTaskPrincipal -UserId $CurrentIdentity -LogonType Interactive -RunLevel Highest
}

Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
Start-Sleep -Milliseconds 500
Stop-MatchingNodeProcesses $RootDir @("run-weixin-service.mjs", "weixin serve")

Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal -Force | Out-Null
Start-ScheduledTask -TaskName $TaskName

Write-Host "Installed scheduled task: $TaskName"
Write-Host "Run as: $($Principal.UserId)"
Write-Host "Home dir: $HomeDir"
Write-Host "Environment file: $EnvFile"
Write-Host "Weixin account: $WeixinAccountId"
Write-Host "Stdout log: $StdoutLog"
Write-Host "Stderr log: $StderrLog"
Write-Host "Status: powershell -ExecutionPolicy Bypass -File scripts/service/status-windows-task.ps1"
